name: 🐛 Сообщение об ошибке
description: Зарегистрировать баг или проблему в работе системы
title: "[BUG] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Спасибо за сообщение об ошибке! Заполните разделы ниже — это поможет быстрее разобраться в проблеме.
  - type: input
    id: title
    attributes:
      label: Заголовок
      description: Кратко опишите суть проблемы одним предложением
      placeholder: "Например: ESP32 перезагружается при длительной работе"
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Описание
      description: |
        Подробно опишите проблему:
        - Что именно не работает?
        - Какие действия привели к проблеме?
        - Какой результат ожидали и какой получили?
      placeholder: "Например: Через 2 часа работы система падает с регистрацией дампа"
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Шаги для воспроизведения
      description: Перечислите чёткие шаги, чтобы воспроизвести ошибку
      placeholder: |
        1. Запустить непрерывный сбор данных с SSVC
        2. На вкладке дампов нет зарегистрированного дампа
        3. Дождаться перезагрузки (≈120 мин)
        4. На вкладке дампов есть новый дамп
    validations:
      required: false
  - type: textarea
    id: expected
    attributes:
      label: Ожидаемое поведение
      description: Опишите, как система должна работать в норме
      placeholder: "Например: Система должна работать стабильно неограниченное время"
    validations:
      required: false
  - type: textarea
    id: actual
    attributes:
      label: Текущее поведение
      description: Опишите, что происходит на самом деле. Можно приложить скриншоты
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Окружение
      description: Укажите версии и компоненты системы
      value: |
        - **Версия прошивки**: 
        - **Версия SSVC**: 
        - **Плата/устройство**: 
        - **Операционная система**: 
        - **Браузер**: (если применимо)
        - **Дополнительные компоненты**: 
      render: markdown
    validations:
      required: false
  - type: textarea
    id: logs
    attributes:
      label: Логи / сообщения об ошибках / дамп прошивки
      description: Вывод консоли, лог-файлы, дампы. Можно перетащить файлы в это поле
      render: shell
    validations:
      required: false
  - type: textarea
    id: context
    attributes:
      label: Дополнительный контекст
      description: |
        - Были ли изменения в конфигурации?
        - Проблема постоянная или периодическая?
        - Есть ли похожие Issue?
    validations:
      required: false
  - type: input
    id: contact
    attributes:
      label: Контактная информация
      description: Опционально. Telegram или Email для связи
      placeholder: "@username или email@example.com"
    validations:
      required: false
